import {Dimensions, StyleSheet} from 'react-native';
const {height, width} = Dimensions.get('window');
const styles = StyleSheet.create({
  profileContainer: {
    position: 'absolute',
    bottom: 138,
    left: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  reelbottomtab: {
    position: 'absolute',
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  discription: {
    position: 'absolute',
    bottom: 100,
    left: 15,
    // flexDirection: 'row',
    // alignItems: 'center',
    width: '80%',
  },
  craditbox: {
    position: 'absolute',
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 12,
    padding: 8,
    borderColor: 'gray',
    width: '60%',
    bottom: 60,
    marginLeft: 10,
  },
  actionCount: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 2,
  },
  musicImage: {
    width: 25,
    height: 25,
    marginTop: 10,
    borderRadius: 50,
    borderColor: 'white',
    borderWidth: 2,
  },
  musicText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 8,
  },
  icon: {
    fontSize: 25,
    color: 'white',
    marginTop: 10,
  },
  camerabtn: {
    position: 'absolute',
    top: 25,
    right: 15,
    flexDirection: 'column',
    alignItems: 'center',
  },
  categoryText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  videocategory: {
    position: 'absolute',
    top: 25,
    left: 15,
    flexDirection: 'column',
    // alignItems: 'center',
  },
  profilePic: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
    backgroundColor: '#15162e',
    borderWidth: 0.5,
    borderColor: 'gray',
  },
  catPic: {
    width: 26,
    height: 26,
    borderRadius: 100,
    borderColor: 'gray',
    borderWidth: 1,
  },
  catname: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'white',
    marginRight: 5,
  },
  description: {
    color: 'white',
    fontSize: 12,
    maxWidth: '100%',
  },
  iconContainer: {
    position: 'absolute',
    right: 10,
    bottom: 80,
    alignItems: 'center',
    // backgroundColor: 'rgba(0,0,0,0.5)',
    // borderRadius:20,
    // padding:5,
    // paddingLeft:10,
    // paddingRight:10,
  },
  iconbackground: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderRadius: 100,
    padding: 10,
    paddingBottom: 8,
    // paddingLeft: 10,
    // paddingRight: 10,
  },
  iconButton: {
    marginBottom: 20,
    alignItems: 'center',
  },
  catButton: {
    flexDirection: 'row',
  },
  iconText: {
    color: 'white',
    marginTop: 5,
    fontSize: 12,
  },
  autoScrollButton: {
    position: 'absolute',
    top: 8,
    left: width / 2 - 25,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
  },
  autoScrollText: {
    color: 'white',
    fontSize: 15,
    textAlign: 'center',
  },
  muteIconContainer: {
    position: 'absolute',
    top: '45%',
    left: '45%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 5,
  },

  profileImage: {
    width: 25,
    height: 25,
    borderRadius: 10,
    borderColor: 'white',
    borderWidth: 1,
    opacity: 0.8,
    backgroundColor: '#15162e',
  },
  profileText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '800',
    marginLeft: 10,
    opacity: 0.7,
  },
  moreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 5,
  },
  moreIcon: {
    width: 15,
    height: 15,
    opacity: 0.7,
  },
  moreText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
    marginLeft: 10,
    opacity: 0.7,
  },
  giflike: {
    position: 'absolute',
    bottom: 50,
    right: 30,
    width: 100,
    height: 100,
  },
  containerLike: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageLike: {
    width: 100,
    height: 100,
    backfaceVisibility: 'hidden', // Hide image during rotation
  },
  reelbtn: {
    width: '48%',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 0,
  },
  reelbtntxt: {
    color: 'white',
    alignSelf: 'center',
    fontSize: 16,
  },
  video: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    borderRadius: 20, // Match the same borderRadius as the container
    zIndex: -1,
  },
});

export default styles;
